apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- coredns.yaml
- nodelocaldns-uw.yaml
- nodelocaldns.yaml
configMapGenerator:
- name: coredns
  namespace: kube-system
  files:
  - coredns-resources/Corefile
- name: node-local-dns
  namespace: kube-system
  files:
  - nodelocaldns-resources/Corefile
