kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-local-dns
  namespace: kube-system
rules:
  # uw config - psp
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
    - node-local-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-local-dns
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-local-dns
subjects:
- kind: ServiceAccount
  name: node-local-dns
  namespace: kube-system
